{
 "title": "HTTP Status (redbox_exporter)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "redbox_success" } },
   { "name": "country", "label": "Country", "query": { "query": "redbox_success" } },
   { "name": "page", "label": "Page", "query": { "query": "redbox_success" } },
   { "name": "name", "label": "Name", "query": { "query": "redbox_success" } },
   { "name": "group", "label": "Group", "query": { "query": "redbox_success" } }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (sum by (name) (redbox_success{group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})) / ((sum by (name) (redbox_success{group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"}) + sum by (name) (redbox_failure{group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Number of Websites down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Websites" }
   ],
   "targets": [
    {
     "expr": "max by (name, err_msg) (redbox_failure{group_group=~\"$group\",group_name=~\"$name\",success=\"0\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group by (name, status_code, extract, err_msg) (redbox_failure{success=\"0\", group_group=~\"$group\", group_name=~\"$name\", group_env=~\"$env\", group_country=~\"$country\", group_page=~\"$page\"})"
    }
   ]
  },
  {
   "title": "HTTP Status Code of down Websites",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Status Code" }
   ],
   "targets": [
    {
     "expr": "max by (name, status_code) (redbox_status_code{success=\"0\",group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}:  {{ status_code }}"
    }
   ]
  },
  {
   "title": "Total Time (OK Websites)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (name) (redbox_time_total{success=\"1\",group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Response Time: Time To First Byte (OK Websites)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (name) (redbox_time_ttfb{success=\"1\",group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Download Time (OK Websites)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (name) (redbox_time_download{success=\"1\",group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Content Size (OK Websites)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (name) (redbox_content_size{success=\"1\",group_group=~\"$group\",group_name=~\"$name\",group_env=~\"$env\",group_country=~\"$country\",group_page=~\"$page\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}