---
# Global settings
global:
  scrape_interval:     60s
  scrape_timeout:      60s
  evaluation_interval: 60s

# Scrape specific settings
scrape_configs:
  - job_name: redbox
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout:  30s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["redbox_exporter:9100"]
